
workspace ‘ShareOCDemo.xcworkspace'
platform :ios, ’9.0’
inhibit_all_warnings!
use_frameworks!

target "ShareOCDemo" do
   pod 'UMCCommon'
   pod 'UMCShare/Social/ReducedWeChat'
   pod 'UMCShare/UI'
#   pod 'UMCShare/Core'
#pod 'UMCSecurityPlugins'

end
